In [22]:
import pandas as pd
from pathlib import Path
from glob import glob

In [23]:
df = pd.read_csv('/home/biodiv/calib/pilot_mnt_data_reconyx-hf2/results/results.csv')
images = pd.read_csv('wildlife-insights_4fc92e40-94fe-48d3-a51f-5ac1a03f5e03_project-2007160_data/images_2007160.csv')
images['deployment_id'] = images['deployment_id'].str.replace('/', '-')

In [24]:
df.columns

Index(['transect_id', 'frame_id', 'detection_idx', 'detection_confidence',
       'depth', 'world_x', 'world_y', 'world_z'],
      dtype='object')

In [25]:
deployment_ids = glob('/home/biodiv/calib/pilot_mnt_data_reconyx-hf2/transects/*')
deployment_ids = [Path(x).name for x in deployment_ids]
deployment_ids

['Cam16 02-10-2024',
 'PM16 02-10-2024',
 'Cam23',
 'PM22 02-10-2024',
 'PM21 02-10-2024']

In [26]:
images = images[images['deployment_id'].isin(deployment_ids)]

In [27]:
images

,project_id,deployment_id,image_id,filename,sequence_id,location,wi_taxon_id,class,order,family,genus,species,common_name,timestamp,bounding_boxes
1033,2007160,Cam23,f84bf378-4ce4-4a4e-8741-be43c7ea40b1,RCNX0013.JPG,8663343,gs://145625598251_2007160_901_pilot_24__main/d...,066c4187-4a03-4531-9f62-ac585ad0a138,Mammalia,Primates,Hominidae,Homo,sapiens,Human-Camera Trapper,2024-02-10 15:40:57,NaN
1034,2007160,Cam23,fbd7b79a-0ea7-4544-ac3f-bede0fc129fa,RCNX0004.JPG,8663343,gs://145625598251_2007160_901_pilot_24__main/d...,066c4187-4a03-4531-9f62-ac585ad0a138,Mammalia,Primates,Hominidae,Homo,sapiens,Human-Camera Trapper,2024-02-10 15:40:40,NaN
1035,2007160,Cam23,6df55d42-bde5-43db-ba76-d6c1b361d4e0,RCNX0025.JPG,8663343,gs://145625598251_2007160_901_pilot_24__main/d...,066c4187-4a03-4531-9f62-ac585ad0a138,Mammalia,Primates,Hominidae,Homo,sapiens,Human-Camera Trapper,2024-02-10 15:41:42,NaN
1036,2007160,Cam23,c5768780-9041-4b9c-aed6-0d3523a58f62,RCNX0006.JPG,8663343,gs://145625598251_2007160_901_pilot_24__main/d...,066c4187-4a03-4531-9f62-ac585ad0a138,Mammalia,Primates,Hominidae,Homo,sapiens,Human-Camera Trapper,2024-02-10 15:40:42,NaN
1037,2007160,Cam23,67a4d5f9-8ed9-4bf8-a061-6864d8fd9d91,RCNX0014.JPG,8663343,gs://145625598251_2007160_901_pilot_24__main/d...,066c4187-4a03-4531-9f62-ac585ad0a138,Mammalia,Primates,Hominidae,Homo,sapiens,Human-Camera Trapper,2024-02-10 15:40:58,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17056,2007160,PM21 02-10-2024,290bdd88-f5b5-4b58-868d-9542f66cd208,RCNX0090.JPG,8662282,gs://145625598251_2007160_901_pilot_24__main/d...,e2f84cfb-5976-4adf-a91d-4953c2916b31,Mammalia,Primates,Hominidae,Homo,sapiens,Human-Faces,2024-03-23 14:29:07,NaN
17057,2007160,PM21 02-10-2024,56845b91-8d7f-4289-8e41-46702e9f0b98,RCNX0113.JPG,8662282,gs://145625598251_2007160_901_pilot_24__main/d...,e2f84cfb-5976-4adf-a91d-4953c2916b31,Mammalia,Primates,Hominidae,Homo,sapiens,Human-Faces,2024-03-23 14:29:43,NaN
17058,2007160,PM21 02-10-2024,69e7c647-570e-499b-88a9-5ae5f8aeebc7,RCNX0089.JPG,8662282,gs://145625598251_2007160_901_pilot_24__main/d...,e2f84cfb-5976-4adf-a91d-4953c2916b31,Mammalia,Primates,Hominidae,Homo,sapiens,Human-Faces,2024-03-23 14:29:06,NaN
17059,2007160,PM21 02-10-2024,53aaa693-9c17-4785-82ea-bf9e9227a133,RCNX0084.JPG,8662282,gs://145625598251_2007160_901_pilot_24__main/d...,e2f84cfb-5976-4adf-a91d-4953c2916b31,Mammalia,Primates,Hominidae,Homo,sapiens,Human-Faces,2024-03-23 14:28:47,"{""{\""detectionBox\"":[0.489147872,0.130072743,0..."
17060,2007160,PM21 02-10-2024,3d4adfd9-d1f4-4a59-979f-1e899f4455fb,RCNX0049.JPG,8662282,gs://145625598251_2007160_901_pilot_24__main/d...,e2f84cfb-5976-4adf-a91d-4953c2916b31,Mammalia,Primates,Hominidae,Homo,sapiens,Human-Faces,2024-03-23 14:26:44,"{""{\""detectionBox\"":[0.295594603,0.119654961,0..."

In [28]:
# images['frame_id'] = images['location'].apply(lambda x: Path(x).stem)
df['image_id'] = df['frame_id']

In [29]:
merged_df = pd.merge(images, df, on='image_id', how='inner')

In [30]:
merged_df

,project_id,deployment_id,image_id,filename,sequence_id,location,wi_taxon_id,class,order,family,...,timestamp,bounding_boxes,transect_id,frame_id,detection_idx,detection_confidence,depth,world_x,world_y,world_z
0,2007160,Cam23,19b1f41a-e009-4e48-bbe1-7ba8c1690e0d,RCNX0440.JPG,8663682,gs://145625598251_2007160_901_pilot_24__main/d...,5c7ce479-8a45-40b3-ae21-7c97dfae22f5,Mammalia,Cetartiodactyla,Cervidae,...,2024-02-15 18:13:45,"{""{\""detectionBox\"":[0.440502971,0.488393962,0...",Cam23,19b1f41a-e009-4e48-bbe1-7ba8c1690e0d,0,0.9582,15.2563,3.1640,2.7453,14.7023
1,2007160,Cam23,87a17fed-fc17-4404-afe3-ca69d4c6af0d,RCNX0539.JPG,8663682,gs://145625598251_2007160_901_pilot_24__main/d...,5c7ce479-8a45-40b3-ae21-7c97dfae22f5,Mammalia,Cetartiodactyla,Cervidae,...,2024-02-15 18:17:49,"{""{\""detectionBox\"":[0.496875554,0.382493138,0...",Cam23,87a17fed-fc17-4404-afe3-ca69d4c6af0d,0,0.9712,14.1405,2.4268,3.4468,13.5403
2,2007160,Cam23,081e0749-7f6c-4815-acc0-be5b9513cded,RCNX0451.JPG,8663682,gs://145625598251_2007160_901_pilot_24__main/d...,5c7ce479-8a45-40b3-ae21-7c97dfae22f5,Mammalia,Cetartiodactyla,Cervidae,...,2024-02-15 18:14:02,"{""{\""detectionBox\"":[0.381236017,0.0789961517,...",Cam23,081e0749-7f6c-4815-acc0-be5b9513cded,0,0.9759,12.5749,-0.7633,2.3897,12.3311
3,2007160,Cam23,0e69278e-a248-45a7-832c-2a786ae0ee03,RCNX0460.JPG,8663682,gs://145625598251_2007160_901_pilot_24__main/d...,5c7ce479-8a45-40b3-ae21-7c97dfae22f5,Mammalia,Cetartiodactyla,Cervidae,...,2024-02-15 18:15:01,"{""{\""detectionBox\"":[0.0249831937,0.049220562,...",Cam23,0e69278e-a248-45a7-832c-2a786ae0ee03,0,0.9744,7.9849,-1.1185,0.0428,7.9076
4,2007160,Cam23,ee9fdc86-6cd2-4aa9-a725-5aa0b538cfb2,RCNX0463.JPG,8663682,gs://145625598251_2007160_901_pilot_24__main/d...,5c7ce479-8a45-40b3-ae21-7c97dfae22f5,Mammalia,Cetartiodactyla,Cervidae,...,2024-02-15 18:15:04,"{""{\""detectionBox\"":[0.0279245917,0.0024384409...",Cam23,ee9fdc86-6cd2-4aa9-a725-5aa0b538cfb2,0,0.9773,13.9759,-2.6654,0.0877,13.7282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1901,2007160,Cam16 02-10-2024,0bbdc3eb-d04b-4334-8052-3b9e1bcc5fd7,RCNX0243.JPG,8668559,gs://145625598251_2007160_901_pilot_24__main/d...,4358855e-64a1-4805-8481-8c6da9f21377,Aves,Piciformes,Picidae,...,2024-02-26 16:53:17,"{""{\""detectionBox\"":[0.54515481,0.920920074,0....",Cam16 02-10-2024,0bbdc3eb-d04b-4334-8052-3b9e1bcc5fd7,0,0.6512,5.3183,3.3720,1.0492,4.4066
1902,2007160,Cam16 02-10-2024,9e7c64b3-b284-45b0-9401-74723d2aa691,RCNX0244.JPG,8668559,gs://145625598251_2007160_901_pilot_24__main/d...,4358855e-64a1-4805-8481-8c6da9f21377,Aves,Piciformes,Picidae,...,2024-02-26 16:53:18,"{""{\""detectionBox\"":[0.482370526,0.55531776,0....",Cam16 02-10-2024,9e7c64b3-b284-45b0-9401-74723d2aa691,0,0.7233,6.3365,1.6981,1.0055,6.0449
1903,2007160,PM16 02-10-2024,3cdf57cb-010e-4118-8ff7-1c68a7fb9d2e,RCNX1092.JPG,8719116,gs://145625598251_2007160_901_pilot_24__main/d...,5c7ce479-8a45-40b3-ae21-7c97dfae22f5,Mammalia,Cetartiodactyla,Cervidae,...,2024-03-22 07:13:14,"{""{\""detectionBox\"":[0.432493299,0.793654621,0...",PM16 02-10-2024,3cdf57cb-010e-4118-8ff7-1c68a7fb9d2e,0,0.4249,23.0244,12.3379,2.4258,20.1826
1904,2007160,PM16 02-10-2024,7ad33397-dd1c-4421-be30-a04f260176cf,RCNX1091.JPG,8719116,gs://145625598251_2007160_901_pilot_24__main/d...,5c7ce479-8a45-40b3-ae21-7c97dfae22f5,Mammalia,Cetartiodactyla,Cervidae,...,2024-03-22 07:13:13,"{""{\""detectionBox\"":[0.439239293,0.857454836,0...",PM16 02-10-2024,7ad33397-dd1c-4421-be30-a04f260176cf,0,0.7884,19.5749,11.5340,2.4096,16.7387
1905,2007160,PM16 02-10-2024,38536560-ef48-49f5-854c-ce870ab689b1,RCNX1090.JPG,8719116,gs://145625598251_2007160_901_pilot_24__main/d...,5c7ce479-8a45-40b3-ae21-7c97dfae22f5,Mammalia,Cetartiodactyla,Cervidae,...,2024-03-22 07:13:12,"{""{\""detectionBox\"":[0.447280675,0.924919724,0...",PM16 02-10-2024,38536560-ef48-49f5-854c-ce870ab689b1,0,0.6099,15.7183,10.0442,1.9072,13.1485

In [31]:
merged_df.to_csv('results-pilot_mnt_data_reconyx-hf2-select-deployments.csv', index=False)

In [34]:
!ls *csv

images_animals.csv  results-pilot_mnt_data_reconyx-hf2-select-deployments.csv
images_human.csv

In [33]:
!croc send results-pilot_mnt_data_reconyx-hf2-select-deployments.csv

Sending 'results-pilot_mnt_data_reconyx-hf2-select-deployments.csv' (918.4 kB)
Code is: 2160-cricket-content-disco
On the other computer run

croc 2160-cricket-content-disco

Sending (->[2605:a601:9137:9e00:245b:b32e:29e5:a756]:51251)
results-pilot_mnt_data_reconyx-hf2-select-deployments.csv 100% |████████████████████| (940/940 kB, 4.1 MB/s)

In [42]:
df_deployments = pd.read_csv('wildlife-insights_4fc92e40-94fe-48d3-a51f-5ac1a03f5e03_project-2007160_data/deployments.csv')

In [43]:
df_images = pd.read_csv('wildlife-insights_4fc92e40-94fe-48d3-a51f-5ac1a03f5e03_project-2007160_data/images_2007160.csv')

In [44]:
merged_df = df_images.merge(df_deployments[['camera_name', 'deployment_id']], on='deployment_id', how='inner')
merged_df

,project_id,deployment_id,image_id,filename,sequence_id,location,wi_taxon_id,class,order,family,genus,species,common_name,timestamp,bounding_boxes,camera_name
0,2007160,cam2 02/10/2024,5be0cdd5-2673-4df0-8c2f-976a0d57ad6a,IMG_0087.JPG,8662421,gs://145625598251_2007160_901_pilot_24__main/d...,5c7ce479-8a45-40b3-ae21-7c97dfae22f5,Mammalia,Cetartiodactyla,Cervidae,Odocoileus,virginianus,White-tailed Deer,2024-02-15 09:25:14,"{""{\""detectionBox\"":[0.471049249,0.290658414,0...",Reconyx HC500 Hyperfire
1,2007160,cam2 02/10/2024,56918fb8-8c46-47af-a9ed-838ccb2e4e99,IMG_0071.JPG,8662421,gs://145625598251_2007160_901_pilot_24__main/d...,5c7ce479-8a45-40b3-ae21-7c97dfae22f5,Mammalia,Cetartiodactyla,Cervidae,Odocoileus,virginianus,White-tailed Deer,2024-02-15 09:24:58,"{""{\""detectionBox\"":[0.349325538,0.75269556,0....",Reconyx HC500 Hyperfire
2,2007160,cam2 02/10/2024,1f1b458d-8940-4540-8236-b10f9b6eff3e,IMG_0073.JPG,8662421,gs://145625598251_2007160_901_pilot_24__main/d...,5c7ce479-8a45-40b3-ae21-7c97dfae22f5,Mammalia,Cetartiodactyla,Cervidae,Odocoileus,virginianus,White-tailed Deer,2024-02-15 09:25:00,"{""{\""detectionBox\"":[0.432572752,0.497536182,0...",Reconyx HC500 Hyperfire
3,2007160,cam2 02/10/2024,d64a32e8-7505-465d-a49a-4222400b78fc,IMG_0090.JPG,8662421,gs://145625598251_2007160_901_pilot_24__main/d...,5c7ce479-8a45-40b3-ae21-7c97dfae22f5,Mammalia,Cetartiodactyla,Cervidae,Odocoileus,virginianus,White-tailed Deer,2024-02-15 09:25:16,"{""{\""detectionBox\"":[0.526797712,0.136983871,0...",Reconyx HC500 Hyperfire
4,2007160,cam2 02/10/2024,b9fc2f9c-8fab-4076-9fa5-9910aec8fae4,IMG_0072.JPG,8662421,gs://145625598251_2007160_901_pilot_24__main/d...,5c7ce479-8a45-40b3-ae21-7c97dfae22f5,Mammalia,Cetartiodactyla,Cervidae,Odocoileus,virginianus,White-tailed Deer,2024-02-15 09:24:59,"{""{\""detectionBox\"":[0.394397795,0.597780347,0...",Reconyx HC500 Hyperfire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17363,2007160,cam23 02/10/2024,e809f663-98a7-4fb9-bdae-a58ca3438e04,IMG_0049.JPG,8722710,gs://145625598251_2007160_901_pilot_24__main/d...,e2f84cfb-5976-4adf-a91d-4953c2916b31,Mammalia,Primates,Hominidae,Homo,sapiens,Human-Faces,2024-03-23 10:27:36,"{""{\""detectionBox\"":[0.385544419,0.00077229738...",Reconyx HC500 Hyperfire
17364,2007160,cam23 02/10/2024,54247801-2617-44e0-98ca-56594b041e52,IMG_0051.JPG,8722710,gs://145625598251_2007160_901_pilot_24__main/d...,e2f84cfb-5976-4adf-a91d-4953c2916b31,Mammalia,Primates,Hominidae,Homo,sapiens,Human-Faces,2024-03-23 10:27:47,"{""{\""detectionBox\"":[0.0200865,0.620940566,0.9...",Reconyx HC500 Hyperfire
17365,2007160,cam23 02/10/2024,38b8d07e-fb33-435f-8b2d-296e053972c7,IMG_0055.JPG,8722710,gs://145625598251_2007160_901_pilot_24__main/d...,e2f84cfb-5976-4adf-a91d-4953c2916b31,Mammalia,Primates,Hominidae,Homo,sapiens,Human-Faces,2024-03-23 10:27:50,"{""{\""detectionBox\"":[0.388210505,0.0008289814,...",Reconyx HC500 Hyperfire
17366,2007160,cam23 02/10/2024,6d89a504-0378-4614-93fb-72a599102e1d,IMG_0054.JPG,8722710,gs://145625598251_2007160_901_pilot_24__main/d...,e2f84cfb-5976-4adf-a91d-4953c2916b31,Mammalia,Primates,Hominidae,Homo,sapiens,Human-Faces,2024-03-23 10:27:49,"{""{\""detectionBox\"":[0.381038338,0.00083452463...",Reconyx HC500 Hyperfire
17367,2007160,cam23 02/10/2024,d1f07932-0876-4fb9-bdb0-ecec90315d5d,IMG_0039.JPG,8722710,gs://145625598251_2007160_901_pilot_24__main/d...,e2f84cfb-5976-4adf-a91d-4953c2916b31,Mammalia,Primates,Hominidae,Homo,sapiens,Human-Faces,2024-03-23 10:27:14,"{""{\""detectionBox\"":[0.443909228,0.660959721,0...",Reconyx HC500 Hyperfire

In [46]:
merged_df['camera_name'].unique()

array(['Reconyx HC500 Hyperfire', 'Reconyx Hyperfire 2',
       'Browning Recon Force Elite', 'HC500 Hyperfire Semi-Covert IR',
       'HC500 Hyperfire Semi-Covert IR_'], dtype=object)

In [51]:
mapping = {
    'HC500 Hyperfire Semi-Covert IR': 'Reconyx HC500 Hyperfire',
    'HC500 Hyperfire Semi-Covert IR_': 'Reconyx HC500 Hyperfire'
}
df['camera_name'] = df['camera_name'].replace(mapping)
df['camera_name'].unique()

array(['Reconyx Hyperfire 2', 'Reconyx HC500 Hyperfire',
       'Browning Recon Force Elite'], dtype=object)

In [52]:
for x in df['camera_name'].unique():
    print(x)

Reconyx Hyperfire 2
Reconyx HC500 Hyperfire
Browning Recon Force Elite

array(['Reconyx HC500 Hyperfire', 'Reconyx Hyperfire 2',
       'Browning Recon Force Elite', 'HC500 Hyperfire Semi-Covert IR',
       'HC500 Hyperfire Semi-Covert IR_'], dtype=object)